import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTimesheetAmendedAt1786720649585 implements MigrationInterface {
    name = 'AddTimesheetAmendedAt1786720649585'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "productions" DROP CONSTRAINT "productions_archived_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP CONSTRAINT "productions_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" DROP CONSTRAINT "cost_plus_budgets_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP CONSTRAINT "cost_plus_budget_lines_budget_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP CONSTRAINT "cost_plus_budget_lines_set_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cost_report_invoices" DROP CONSTRAINT "cost_report_invoices_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP CONSTRAINT "crew_documents_crew_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP CONSTRAINT "crew_documents_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP CONSTRAINT "forecasts_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP CONSTRAINT "forecasts_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" DROP CONSTRAINT "forecast_labour_items_forecast_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" DROP CONSTRAINT "forecast_materials_items_forecast_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" DROP CONSTRAINT "forecast_materials_items_supplier_catalogue_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "pay_runs_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "pay_runs_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "timesheets_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "timesheets_crew_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "timesheets_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" DROP CONSTRAINT "pay_run_items_crew_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" DROP CONSTRAINT "pay_run_items_pay_run_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" DROP CONSTRAINT "pay_run_items_timesheet_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "production_crew" DROP CONSTRAINT "production_crew_crew_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "production_crew" DROP CONSTRAINT "production_crew_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP CONSTRAINT "production_documents_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP CONSTRAINT "production_documents_uploaded_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "sets" DROP CONSTRAINT "sets_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_approved_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_production_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP CONSTRAINT "timesheet_entries_timesheet_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."bectu_rates_trade_rank_effective"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bectu_rates_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_budget_lines_budget_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_forecasts_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_forecasts_primary_per_production"`);
        await queryRunner.query(`DROP INDEX "public"."idx_supplier_catalogue_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."timesheets_crew_prod_week_uniq"`);
        await queryRunner.query(`DROP INDEX "public"."idx_percentometer_ratios_active_cost_type"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP CONSTRAINT "productions_contract_type_check"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP CONSTRAINT "productions_status_check"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP CONSTRAINT "crew_members_employment_status_check"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP CONSTRAINT "crew_documents_document_type_check"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "pay_runs_status_check"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "timesheets_status_check"`);
        await queryRunner.query(`ALTER TABLE "sets" DROP CONSTRAINT "sets_completion_status_check"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_paid_from_check"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_status_check"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP CONSTRAINT "bectu_rates_trade_rank_rate_year_key"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "pay_runs_production_id_week_ending_date_key"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "timesheets_crew_member_id_production_id_week_ending_date_key"`);
        await queryRunner.query(`ALTER TABLE "production_crew" DROP CONSTRAINT "production_crew_production_id_crew_member_id_key"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP COLUMN "effective_from"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP COLUMN "effective_to"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP COLUMN "rate_type"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "archived_at"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "archived_by"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "post_production_percentometer"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "target_profit_pct"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "agreed_price"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP COLUMN "rollback_notice"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "bectu_rate"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "agreed_rate"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "line_margin_rate"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "is_above_line"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "set_id"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP COLUMN "line_type"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "qualifications"`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "company_utr"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP COLUMN "file_size"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP COLUMN "context_type"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP COLUMN "file_key"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP COLUMN "file_mime_type"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP COLUMN "percentometer_snapshot"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP COLUMN "is_primary"`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" DROP COLUMN "daily_rate"`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" DROP COLUMN "ot_rate"`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP COLUMN "rate_override"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP COLUMN "rank_override"`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" DROP COLUMN "effective_from"`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" DROP COLUMN "effective_to"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP COLUMN "file_size"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP COLUMN "file_key"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP COLUMN "file_mime_type"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "supplier_code"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "street_name"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "zip_code"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "county"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "meal_allowance_breakfast"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "meal_allowance_lunch"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "meal_allowance_supper"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "mileage"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "per_diem"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP COLUMN "ad_hoc_reimbursement"`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD "amended_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ALTER COLUMN "rate_year" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "margin_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "margin_rate" SET DEFAULT '0.1'`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "contracted_weeks" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "weekly_cost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "weeks" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_report_invoices" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "date_of_birth" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "paye_withholding_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ALTER COLUMN "uploaded_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "total_labour_cost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "total_materials_cost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "total_forecast_cost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "number_of_crew" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "number_of_weeks" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "overtime_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ALTER COLUMN "quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "weekly_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "sixth_day_payment" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "seventh_day_payment" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "overtime_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "meal_allowance_total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "mileage_and_travel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "vat" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "gross_total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "grand_total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ALTER COLUMN "withholding_amount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" ADD CONSTRAINT "UQ_3027ee9f13e4404dacdb84b1ded" UNIQUE ("cost_type")`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "production_crew" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "production_documents" ALTER COLUMN "uploaded_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sets" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sets" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "date_of_po" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "vat" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "full_day_worked" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "overtime_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "travel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "meal_breakfast" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "meal_lunch" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "meal_supper" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD CONSTRAINT "UQ_b5eb55e3a7ec27f48c53aed0914" UNIQUE ("trade", "rank", "rate_year")`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "UQ_5d7afe377f0562611dd58812524" UNIQUE ("production_id", "week_ending_date")`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "UQ_6b8ea3801d2870be1f7f9d57d10" UNIQUE ("crew_member_id", "production_id", "week_ending_date")`);
        await queryRunner.query(`ALTER TABLE "production_crew" ADD CONSTRAINT "UQ_fe0dc2071621d153252e8f6c5d3" UNIQUE ("production_id", "crew_member_id")`);
        await queryRunner.query(`ALTER TABLE "productions" ADD CONSTRAINT "FK_12f635582bbab529584078ef3dc" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ADD CONSTRAINT "FK_11651c7b64a490ee728f65d5862" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD CONSTRAINT "FK_0ab63f73c9397029939865f6e0f" FOREIGN KEY ("budget_id") REFERENCES "cost_plus_budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_report_invoices" ADD CONSTRAINT "FK_c8e009ebec6022ae83070915940" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD CONSTRAINT "FK_b7b268e7db595c503b56058038f" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD CONSTRAINT "FK_625be02bcd24514fa20e6f83051" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD CONSTRAINT "FK_3683ebbbc7e57c55a1a039700be" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD CONSTRAINT "FK_ef3c7c46cfea18dd877d7351d18" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ADD CONSTRAINT "FK_d21dc7ebfaeb9d236a1f0ba54e7" FOREIGN KEY ("forecast_id") REFERENCES "forecasts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ADD CONSTRAINT "FK_4b7a9743f816859a3a7a74e1272" FOREIGN KEY ("forecast_id") REFERENCES "forecasts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ADD CONSTRAINT "FK_fa24994e52be69851a9f224eb1d" FOREIGN KEY ("supplier_catalogue_id") REFERENCES "supplier_catalogue"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "FK_bb43405adacedce51473d87a2ef" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "FK_7d8432c7a1c654716bee4386b51" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_875f0ad5814a3540cea3ae83ead" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_7bde9a20089abb3a1f0a3899d3c" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_12aea6e2736fad11ec99c495e78" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ADD CONSTRAINT "FK_460e733ed160bde2eb32a2eb2ff" FOREIGN KEY ("pay_run_id") REFERENCES "pay_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ADD CONSTRAINT "FK_a928bbbc5addf2429f5fb5fb5a4" FOREIGN KEY ("timesheet_id") REFERENCES "timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ADD CONSTRAINT "FK_57baed326fa4b416825ba1005d8" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_crew" ADD CONSTRAINT "FK_b96acfe260c6f5dfffc20594de6" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_crew" ADD CONSTRAINT "FK_d0e33ca6a0fafa7f60478f5eba6" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD CONSTRAINT "FK_7f0eec0a642a2587ed95b5ae68e" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD CONSTRAINT "FK_a4fa052eace861ed0aa9c9b2c32" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sets" ADD CONSTRAINT "FK_d6bdaea55d05aca2014c00d7a03" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_6f3fd57a94a668ed26e2fbdf099" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD CONSTRAINT "FK_1619112e6d4c2ba65a676595bbe" FOREIGN KEY ("timesheet_id") REFERENCES "timesheets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP CONSTRAINT "FK_1619112e6d4c2ba65a676595bbe"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_396e7d9c9ddef24e5af83a23316"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_6f3fd57a94a668ed26e2fbdf099"`);
        await queryRunner.query(`ALTER TABLE "sets" DROP CONSTRAINT "FK_d6bdaea55d05aca2014c00d7a03"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP CONSTRAINT "FK_a4fa052eace861ed0aa9c9b2c32"`);
        await queryRunner.query(`ALTER TABLE "production_documents" DROP CONSTRAINT "FK_7f0eec0a642a2587ed95b5ae68e"`);
        await queryRunner.query(`ALTER TABLE "production_crew" DROP CONSTRAINT "FK_d0e33ca6a0fafa7f60478f5eba6"`);
        await queryRunner.query(`ALTER TABLE "production_crew" DROP CONSTRAINT "FK_b96acfe260c6f5dfffc20594de6"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" DROP CONSTRAINT "FK_57baed326fa4b416825ba1005d8"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" DROP CONSTRAINT "FK_a928bbbc5addf2429f5fb5fb5a4"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" DROP CONSTRAINT "FK_460e733ed160bde2eb32a2eb2ff"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_12aea6e2736fad11ec99c495e78"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_7bde9a20089abb3a1f0a3899d3c"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_875f0ad5814a3540cea3ae83ead"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "FK_7d8432c7a1c654716bee4386b51"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "FK_bb43405adacedce51473d87a2ef"`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" DROP CONSTRAINT "FK_fa24994e52be69851a9f224eb1d"`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" DROP CONSTRAINT "FK_4b7a9743f816859a3a7a74e1272"`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" DROP CONSTRAINT "FK_d21dc7ebfaeb9d236a1f0ba54e7"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP CONSTRAINT "FK_ef3c7c46cfea18dd877d7351d18"`);
        await queryRunner.query(`ALTER TABLE "forecasts" DROP CONSTRAINT "FK_3683ebbbc7e57c55a1a039700be"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP CONSTRAINT "FK_625be02bcd24514fa20e6f83051"`);
        await queryRunner.query(`ALTER TABLE "crew_documents" DROP CONSTRAINT "FK_b7b268e7db595c503b56058038f"`);
        await queryRunner.query(`ALTER TABLE "cost_report_invoices" DROP CONSTRAINT "FK_c8e009ebec6022ae83070915940"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" DROP CONSTRAINT "FK_0ab63f73c9397029939865f6e0f"`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" DROP CONSTRAINT "FK_11651c7b64a490ee728f65d5862"`);
        await queryRunner.query(`ALTER TABLE "productions" DROP CONSTRAINT "FK_12f635582bbab529584078ef3dc"`);
        await queryRunner.query(`ALTER TABLE "production_crew" DROP CONSTRAINT "UQ_fe0dc2071621d153252e8f6c5d3"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "UQ_6b8ea3801d2870be1f7f9d57d10"`);
        await queryRunner.query(`ALTER TABLE "pay_runs" DROP CONSTRAINT "UQ_5d7afe377f0562611dd58812524"`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" DROP CONSTRAINT "UQ_b5eb55e3a7ec27f48c53aed0914"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "meal_supper" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "meal_lunch" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "meal_breakfast" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "travel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "overtime_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ALTER COLUMN "full_day_worked" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "vat" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "date_of_po" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "sets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "production_documents" ALTER COLUMN "uploaded_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "production_crew" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" DROP CONSTRAINT "UQ_3027ee9f13e4404dacdb84b1ded"`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ALTER COLUMN "withholding_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "grand_total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "gross_total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "vat" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "mileage_and_travel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "meal_allowance_total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "overtime_amount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "seventh_day_payment" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "sixth_day_payment" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" ALTER COLUMN "weekly_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ALTER COLUMN "quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "overtime_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "number_of_weeks" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ALTER COLUMN "number_of_crew" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "total_forecast_cost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "total_materials_cost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "forecasts" ALTER COLUMN "total_labour_cost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ALTER COLUMN "uploaded_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" ALTER COLUMN "paye_withholding_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crew_members" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "date_of_birth" date`);
        await queryRunner.query(`ALTER TABLE "cost_report_invoices" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "weeks" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ALTER COLUMN "weekly_cost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "contracted_weeks" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "margin_rate" SET DEFAULT 0.10`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ALTER COLUMN "margin_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ALTER COLUMN "rate_year" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP COLUMN "amended_at"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "ad_hoc_reimbursement" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "per_diem" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "mileage" numeric DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "meal_allowance_supper" numeric(6,2)`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "meal_allowance_lunch" numeric(6,2)`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD "meal_allowance_breakfast" numeric(6,2)`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "department" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "county" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "city" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "zip_code" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "street_name" text`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "supplier_code" text`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD "file_mime_type" text`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD "file_key" text`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD "file_size" bigint`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" ADD "effective_to" date`);
        await queryRunner.query(`ALTER TABLE "percentometer_ratios" ADD "effective_from" date NOT NULL DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD "rank_override" text`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD "rate_override" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "supplier_catalogue" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ADD "ot_rate" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ADD "daily_rate" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD "is_primary" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD "percentometer_snapshot" jsonb`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD "file_mime_type" text`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD "file_key" text`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD "context_type" text`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD "file_size" bigint`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "company_utr" text`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD "qualifications" text array DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "line_type" character varying(20) NOT NULL DEFAULT 'set'`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "set_id" uuid`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "is_above_line" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "line_margin_rate" numeric(5,4)`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "agreed_rate" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD "bectu_rate" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "rollback_notice" text`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "agreed_price" numeric(14,2)`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "target_profit_pct" numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "post_production_percentometer" jsonb`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "archived_by" uuid`);
        await queryRunner.query(`ALTER TABLE "productions" ADD "archived_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD "rate_type" text DEFAULT 'bectu'`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD "effective_to" date`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD "effective_from" date`);
        await queryRunner.query(`ALTER TABLE "production_crew" ADD CONSTRAINT "production_crew_production_id_crew_member_id_key" UNIQUE ("production_id", "crew_member_id")`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "timesheets_crew_member_id_production_id_week_ending_date_key" UNIQUE ("crew_member_id", "production_id", "week_ending_date")`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "pay_runs_production_id_week_ending_date_key" UNIQUE ("production_id", "week_ending_date")`);
        await queryRunner.query(`ALTER TABLE "bectu_rates" ADD CONSTRAINT "bectu_rates_trade_rank_rate_year_key" UNIQUE ("trade", "rank", "rate_year")`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'submitted'::text, 'issued'::text, 'invoice_received'::text, 'approved'::text])))`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_paid_from_check" CHECK ((paid_from = ANY (ARRAY['supplier_account'::text, 'arbuthnot_current_account'::text, 'charge_card'::text, 'pleo_charge_card'::text])))`);
        await queryRunner.query(`ALTER TABLE "sets" ADD CONSTRAINT "sets_completion_status_check" CHECK ((completion_status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'nearing_completion'::text, 'complete'::text, 'handed_over'::text])))`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "timesheets_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'distributed'::text, 'amendment_requested'::text, 'finalised'::text])))`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "pay_runs_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'processed'::text])))`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD CONSTRAINT "crew_documents_document_type_check" CHECK ((document_type = ANY (ARRAY['government_id'::text, 'contract'::text, 'other'::text])))`);
        await queryRunner.query(`ALTER TABLE "crew_members" ADD CONSTRAINT "crew_members_employment_status_check" CHECK ((employment_status = ANY (ARRAY['paye'::text, 'self_employed'::text])))`);
        await queryRunner.query(`ALTER TABLE "productions" ADD CONSTRAINT "productions_status_check" CHECK ((status = ANY (ARRAY['pre_production'::text, 'active_build'::text, 'strike'::text, 'complete'::text, 'archived'::text])))`);
        await queryRunner.query(`ALTER TABLE "productions" ADD CONSTRAINT "productions_contract_type_check" CHECK ((contract_type = ANY (ARRAY['on_a_price'::text, 'cost_plus'::text])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK ((role = ANY (ARRAY['managing_director'::text, 'construction_accountant'::text, 'construction_coordinator'::text])))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_percentometer_ratios_active_cost_type" ON "percentometer_ratios" USING btree ("cost_type") WHERE (effective_to IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "timesheets_crew_prod_week_uniq" ON "timesheets" USING btree ("crew_member_id", "production_id", "week_ending_date") `);
        await queryRunner.query(`CREATE INDEX "idx_supplier_catalogue_deleted" ON "supplier_catalogue" USING btree ("deleted_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_forecasts_primary_per_production" ON "forecasts" USING btree ("production_id") WHERE ((is_primary = true) AND (production_id IS NOT NULL) AND (deleted_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_forecasts_deleted" ON "forecasts" USING btree ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_budget_lines_budget_id" ON "cost_plus_budget_lines" USING btree ("budget_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bectu_rates_active" ON "bectu_rates" USING btree ("effective_to") WHERE (effective_to IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "bectu_rates_trade_rank_effective" ON "bectu_rates" USING btree ("effective_from", "rank", "trade") `);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD CONSTRAINT "timesheet_entries_timesheet_id_fkey" FOREIGN KEY ("timesheet_id") REFERENCES "timesheets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sets" ADD CONSTRAINT "sets_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD CONSTRAINT "production_documents_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_documents" ADD CONSTRAINT "production_documents_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_crew" ADD CONSTRAINT "production_crew_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_crew" ADD CONSTRAINT "production_crew_crew_member_id_fkey" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ADD CONSTRAINT "pay_run_items_timesheet_id_fkey" FOREIGN KEY ("timesheet_id") REFERENCES "timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ADD CONSTRAINT "pay_run_items_pay_run_id_fkey" FOREIGN KEY ("pay_run_id") REFERENCES "pay_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_run_items" ADD CONSTRAINT "pay_run_items_crew_member_id_fkey" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "timesheets_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "timesheets_crew_member_id_fkey" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "timesheets_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "pay_runs_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pay_runs" ADD CONSTRAINT "pay_runs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ADD CONSTRAINT "forecast_materials_items_supplier_catalogue_id_fkey" FOREIGN KEY ("supplier_catalogue_id") REFERENCES "supplier_catalogue"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_materials_items" ADD CONSTRAINT "forecast_materials_items_forecast_id_fkey" FOREIGN KEY ("forecast_id") REFERENCES "forecasts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecast_labour_items" ADD CONSTRAINT "forecast_labour_items_forecast_id_fkey" FOREIGN KEY ("forecast_id") REFERENCES "forecasts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD CONSTRAINT "forecasts_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forecasts" ADD CONSTRAINT "forecasts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD CONSTRAINT "crew_documents_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crew_documents" ADD CONSTRAINT "crew_documents_crew_member_id_fkey" FOREIGN KEY ("crew_member_id") REFERENCES "crew_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_report_invoices" ADD CONSTRAINT "cost_report_invoices_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD CONSTRAINT "cost_plus_budget_lines_set_id_fkey" FOREIGN KEY ("set_id") REFERENCES "sets"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budget_lines" ADD CONSTRAINT "cost_plus_budget_lines_budget_id_fkey" FOREIGN KEY ("budget_id") REFERENCES "cost_plus_budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_plus_budgets" ADD CONSTRAINT "cost_plus_budgets_production_id_fkey" FOREIGN KEY ("production_id") REFERENCES "productions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productions" ADD CONSTRAINT "productions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productions" ADD CONSTRAINT "productions_archived_by_fkey" FOREIGN KEY ("archived_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
